### Site Settings ###
title               : Alex Kramer
position            : Ph.D. student
affiliation         : Department of Linguistics, University of Michigan
description         : >-
                      I study the relationship between language processing and (contact-induced) language change using tools from experimental syntax and computational linguistics.
baseurl             : "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : narquelion/narquelion.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


gems:
  - jekyll-webmention_io

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html


### Author Info ###
author:
  name                   : Alex Kramer
  image                  : /assets/images/profileimg.jpg
  image-full             : /assets/images/profileimg_full.jpg
  homepage               : alexkramer.io
  locality               : Ann Arbor
  province               : MI
  country                : USA
  languages:
      - name: English
        code: en-US
        proficiency: native
      - name: Japanese
        code: ja
        proficiency: advanced/fluent
      - name: Russian
        code: ru
        proficiency: intermediate
  handles :
     - Narquelion
     - Alexeme
  nicknames:
     - Nico
     - Nick
  email-academic         : arkram AT umich DOT edu
  email-other            : alex AT alexkramer DOT io
  birthday               : --10-18
  gender                 : Agender/Non-binary
  pronouns-pref          : they&#47;them&#47;theirs
  pronouns-other         : he&#47;him&#47;his
  pronouns-other-example : он&#47;его
  dietary-preference     : omnivore
  accounts:
      github             : Narquelion
# instagram              : your_username
# linkedin               : your_username
# medium                 : your_username
# soundcloud             : your_username
# spotify                : your_username
# stackoverflow          : your_user_id
# tumblr                 : your_username.tumblr.com
# twitch                 : your_username
      twitter                : _alexeme
# youtube                : your_channel_name
      orcid                  : 0000-0002-0509-1453
      osf                    : ubas9
      google-scholar         : citations?user=8VsVQ2UAAAAJ

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"


webmentions:
  author:
    photo: /assets/images/profileimg.jpg
  username: alexkramer.io
  # Use my own cache folder
  cache_folder: .cache
  # skip bad URLs for 5 days
  cache_bad_uris_for: 5
  js: true
