# User config
author: "Alex Kramer / Ph.D. student, University of Michigan Department of Linguistics"
tagline: "Ph.D. student, University of Michigan Department of Linguistics"
description: "I study language contact and contact-induced change from a psycholinguistic and computational perspective."
keywords: "Linguistics, Language Contact, Morphosyntax"
email: "arkram@umich.edu"
github: "https://github.com/Narquelion"

links:
  - link:
    url: "/cv"
    title: "CV"
    text: "cv"
    next: true
  - link:
    url: "/alexeme"
    title: "about"
    text: "about"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
